# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    # times = 0
    # question_list = []
    def __init__(self):
        self.i = 0
        self.string = []
        self.length = len(self.string)
        self.ans = list(range(3))
        self.total_num_wr = 0
        self.total_num_cor = 0

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(891, 908)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(300, 20, 281, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(270, 280, 181, 61))
        self.btn_start.setObjectName("btn_start")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 90, 621, 91))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 170, 481, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 220, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.prev = QtWidgets.QPushButton(self.centralwidget)
        self.prev.setGeometry(QtCore.QRect(80, 760, 81, 51))
        self.prev.setObjectName("prev")
        self.choice4 = QtWidgets.QCheckBox(self.centralwidget)
        self.choice4.setGeometry(QtCore.QRect(80, 630, 771, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.choice4.setFont(font)
        self.choice4.setObjectName("choice4")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(330, 760, 91, 51))
        self.submit.setObjectName("submit")
        self.choice1 = QtWidgets.QCheckBox(self.centralwidget)
        self.choice1.setGeometry(QtCore.QRect(80, 380, 751, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.choice1.setFont(font)
        self.choice1.setObjectName("choice1")
        self.qn_name = QtWidgets.QLabel(self.centralwidget)
        self.qn_name.setGeometry(QtCore.QRect(70, 290, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.qn_name.setFont(font)
        self.qn_name.setObjectName("qn_name")
        self.next = QtWidgets.QPushButton(self.centralwidget)
        self.next.setGeometry(QtCore.QRect(640, 760, 91, 51))
        self.next.setObjectName("next")
        self.choice2 = QtWidgets.QCheckBox(self.centralwidget)
        self.choice2.setGeometry(QtCore.QRect(80, 460, 771, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.choice2.setFont(font)
        self.choice2.setObjectName("choice2")
        self.choice3 = QtWidgets.QCheckBox(self.centralwidget)
        self.choice3.setGeometry(QtCore.QRect(80, 550, 761, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.choice3.setFont(font)
        self.choice3.setObjectName("choice3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 891, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        self.btn_start.clicked.connect(self.start_test)
        self.next.clicked.connect(self.next_question)
        self.prev.clicked.connect(self.prev_question)
        self.choice1.clicked.connect(self.chooseA)
        self.choice2.clicked.connect(self.chooseB)
        self.choice3.clicked.connect(self.chooseC)
        self.choice4.clicked.connect(self.chooseD)
        self.submit.clicked.connect(self.calcTotal)

        self.qn_name.setVisible(False)
        self.choice1.setVisible(False)
        self.choice2.setVisible(False)
        self.choice3.setVisible(False)
        self.choice4.setVisible(False)
        self.prev.setVisible(False)
        self.submit.setVisible(False)
        self.next.setVisible(False)



    # def prepare_test(self):
    #     self.btn_start.setVisible(False)
    #     self.label_3.setVisible(False)
    #
    #     file = open("questions.txt", "r")
    #     # answer_list = ["A", "B", "C", "D"]
    #     # selected_answer = []
    #     question_list = file.readlines()
    #     # self.qn_name.setVisible(True)
    #     # self.answer1.setVisible(True)
    #     print(question_list)
    #     times = len(question_list) // 6
    #
    #     count = 0
    #
    #     self.start_test(count, times, question_list)

    def start_test(self):

        self.btn_start.setVisible(False)
        self.label_3.setVisible(False)

        self.qn_name.setVisible(True)
        self.choice1.setVisible(True)
        self.choice2.setVisible(True)
        self.choice3.setVisible(True)
        self.choice4.setVisible(True)
        self.next.setVisible(True)
        self.prev.setVisible(True)
        self.submit.setVisible(True)

        ques = []
        with open('questions.txt', encoding='utf-8-sig', mode='r') as file:
            ques = file.readlines()
        # print(ques)
        ques = [x.strip() for x in ques]
        ques.apppend('')
        print(ques)
        check = ['A', 'B', 'C', 'D']
        total = 1
        tmp = ''
        c = 0
        for i in range(len(ques)):
            tmp += ques[i] + '\n'
            if ques[i] == '':
                self.string.append(tmp)
                tmp = ''
                c += 1
        self.length = c
        self.i = 0
        self.reset()
        self.textBrowser.setText(self.string[self.i])
        print(self.string)
        print(c)


    def prev_question(self):
        self.reset()
        if self.i ==0:
            self.i = 0
        else:
            self.i -= 1
            self.textBrowser.setText(self.string[self.i])

    def next_question(self, count, times, question_list):
        self.reset()
        if self.i == (self.length -1):
            self.i = (self.length -1)
        else:
            self.i +=1
            self.textBrowser.settext(self.string[self.i])

    def reset(self):
        self.aButton.setChecked(False)
        self.bButton.setChecked(False)
        self.cButton.setChecked(False)
        self.dButton.setChecked(False)

    def chooseA(self):
        print(self.ans)
        self.ans[self.i] = 'A'
        print(self.ans)

    def chooseB(self):
        print(self.ans)
        self.ans[self.i] = 'B'
        print(self.ans)

    def chooseC(self):
        print(self.ans)
        self.ans[self.i] = 'C'
        print(self.ans)

    def chooseD(self):
        print(self.ans)
        self.ans[self.i] = 'D'
        print(self.ans)


    def calcTotal(self):
        with open('answer.txt', encoding='utf-8-sig', mode='r') as file:
            cor = file.readlines()
        cor = [x.strip() for x in cor]

        ques_wrong = []
        for x in range(self.length):
            if self.ans[x] != cor[x][-1:]:
                self.total_num_wr += 1
                ques_wrong.append(x+1)

        self.total_num_cor = self.length - self.total_num_wr

        msg = QtWidgets.QMessageBox()
        msg.setIcon(QtWidgets.QMessageBox.Information)
        msg.setText("BẠN {} {}!".format("ĐÃ" if self.total_num_cor >= 2 else "KHÔNG", "VƯỢT QUA BÀI THI!"))
        msg.setInformativeText("Số câu đúng: {} \n"
                               "Số câu sai: {}".format(self.total_num_cor, self.total_num_wr))

        msg.setWindowTitle("Kết quả")
        msg.exec_()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Driver License Test"))
        self.btn_start.setText(_translate("MainWindow", "Start"))
        self.label.setText(_translate("MainWindow", "Welcome to Driver License Test!"))
        self.label_2.setText(_translate("MainWindow", "Try to finish as much as possible questions to pass the test."))
        self.label_3.setText(_translate("MainWindow", "GOOD LUCK !"))
        self.prev.setText(_translate("MainWindow", "Previous"))
        self.choice4.setText(_translate("MainWindow", "D"))
        self.submit.setText(_translate("MainWindow", "Submit"))
        self.choice1.setText(_translate("MainWindow", "A"))
        self.qn_name.setText(_translate("MainWindow", "Question"))
        self.next.setText(_translate("MainWindow", "Next"))
        self.choice2.setText(_translate("MainWindow", "B"))
        self.choice3.setText(_translate("MainWindow", "C"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
