# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 10, 191, 31))
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(60, 70, 331, 91))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 71, 21))
        self.label_2.setObjectName("label_2")
        self.fullname = QtWidgets.QLineEdit(self.groupBox)
        self.fullname.setGeometry(QtCore.QRect(80, 20, 241, 21))
        self.fullname.setObjectName("fullname")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 51, 16))
        self.label_3.setObjectName("label_3")
        self.sex = QtWidgets.QComboBox(self.groupBox)
        self.sex.setGeometry(QtCore.QRect(80, 60, 91, 21))
        self.sex.setObjectName("sex")
        self.sex.addItem("")
        self.sex.addItem("")
        self.sex.addItem("")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(60, 190, 271, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.service1 = QtWidgets.QCheckBox(self.groupBox_2)
        self.service1.setGeometry(QtCore.QRect(20, 30, 71, 21))
        self.service1.setObjectName("service1")
        self.service2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.service2.setGeometry(QtCore.QRect(150, 30, 71, 16))
        self.service2.setObjectName("service2")
        self.Service3 = QtWidgets.QSpinBox(self.groupBox_2)
        self.Service3.setGeometry(QtCore.QRect(150, 60, 42, 22))
        self.Service3.setObjectName("Service3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(70, 60, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(70, 100, 47, 13))
        self.label_5.setObjectName("label_5")
        self.service4 = QtWidgets.QSpinBox(self.groupBox_2)
        self.service4.setGeometry(QtCore.QRect(150, 90, 42, 22))
        self.service4.setObjectName("service4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(50, 340, 221, 31))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.total = QtWidgets.QLineEdit(self.groupBox_3)
        self.total.setGeometry(QtCore.QRect(100, 0, 113, 20))
        self.total.setObjectName("total")
        self.calcBtn = QtWidgets.QPushButton(self.centralwidget)
        self.calcBtn.setGeometry(QtCore.QRect(40, 340, 75, 23))
        self.calcBtn.setObjectName("calcBtn")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(290, 340, 47, 13))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.calcBtn.clicked.connect(self.calcTotal)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Clinic Billing Application"))
        self.groupBox.setTitle(_translate("MainWindow", "Customer\'s information"))
        self.label_2.setText(_translate("MainWindow", "Fullname: "))
        self.label_3.setText(_translate("MainWindow", "Gender:"))
        self.sex.setItemText(0, _translate("MainWindow", "Female"))
        self.sex.setItemText(1, _translate("MainWindow", "Male"))
        self.sex.setItemText(2, _translate("MainWindow", "Other"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Service"))
        self.service1.setText(_translate("MainWindow", "Service1"))
        self.service2.setText(_translate("MainWindow", "Service2"))
        self.label_4.setText(_translate("MainWindow", "Service3"))
        self.label_5.setText(_translate("MainWindow", "Service4"))
        self.calcBtn.setText(_translate("MainWindow", "Total"))
        self.label_6.setText(_translate("MainWindow", "vnd"))


    def calcTotal(self):
        print("Press button")
        print("Fullname:", self.fullname.text())
        print("Sex:", self.sex.currentText())
        print("Service1", self.service1.checkState())
        print("Service2", self.service2.checkState())
        print("Service3", self.service3.text())
        print("Service4", self.service4.text())

        prices = {
            "Service1": 100000,
            "Service2": 200000,
            "Service3": 50000,
            "Service4": 500000,
        }
        sum = (0 if self.service1.checkState() == 0 else prices["Service1"]) \
              + (0 if self.service2.checkState() == 0 else prices["Service2"]) \
              + int(self.service3.text()) * prices["Service3"] \
              + int(self.service4.text()) * prices["Service4"]
        print(sum)
        self.total.setText(str(sum))

        msg = QtWidgets.QMessageBox()
        msg.setIcon(QtWidgets.QMessageBox.Information)
        msg.setText("Chào {} {}!".format("Ông" if self.sex.currentText() == "Nam" else "Bà", self.fullname.text()))
        msg.setInformativeText(" Tổng chi phí là {}vnđ".format(str(sum)))
        msg.setWindowTitle("Chi phí")
        msg.exec_()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
