# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'total_service.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 10, 191, 31))
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(60, 70, 331, 91))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 71, 21))
        self.label_2.setObjectName("label_2")
        self.fullname = QtWidgets.QLineEdit(self.groupBox)
        self.fullname.setGeometry(QtCore.QRect(80, 20, 241, 21))
        self.fullname.setObjectName("fullname")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 51, 16))
        self.label_3.setObjectName("label_3")
        self.gender = QtWidgets.QComboBox(self.groupBox)
        self.gender.setGeometry(QtCore.QRect(80, 60, 91, 21))
        self.gender.setObjectName("gender")
        self.gender.addItem("")
        self.gender.addItem("")
        self.gender.addItem("")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(60, 190, 271, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.Service1 = QtWidgets.QCheckBox(self.groupBox_2)
        self.Service1.setGeometry(QtCore.QRect(20, 30, 71, 21))
        self.Service1.setObjectName("Service1")
        self.Service2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.Service2.setGeometry(QtCore.QRect(150, 30, 71, 16))
        self.Service2.setObjectName("Service2")
        self.Service3 = QtWidgets.QSpinBox(self.groupBox_2)
        self.Service3.setGeometry(QtCore.QRect(150, 60, 42, 22))
        self.Service3.setObjectName("Service3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(70, 60, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(70, 100, 47, 13))
        self.label_5.setObjectName("label_5")
        self.Service3_2 = QtWidgets.QSpinBox(self.groupBox_2)
        self.Service3_2.setGeometry(QtCore.QRect(150, 90, 42, 22))
        self.Service3_2.setObjectName("Service3_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(60, 370, 291, 71))
        self.groupBox_3.setObjectName("groupBox_3")
        self.clacBtn = QtWidgets.QPushButton(self.groupBox_3)
        self.clacBtn.setGeometry(QtCore.QRect(10, 30, 75, 23))
        self.clacBtn.setObjectName("clacBtn")
        self.total_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.total_2.setGeometry(QtCore.QRect(110, 30, 113, 20))
        self.total_2.setObjectName("total_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Clinic Billing Application"))
        self.groupBox.setTitle(_translate("MainWindow", "Customer\'s information"))
        self.label_2.setText(_translate("MainWindow", "Fullname: "))
        self.label_3.setText(_translate("MainWindow", "Gender:"))
        self.gender.setItemText(0, _translate("MainWindow", "Female"))
        self.gender.setItemText(1, _translate("MainWindow", "Male"))
        self.gender.setItemText(2, _translate("MainWindow", "Other"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Service"))
        self.Service1.setText(_translate("MainWindow", "Service1"))
        self.Service2.setText(_translate("MainWindow", "Service2"))
        self.label_4.setText(_translate("MainWindow", "Service3"))
        self.label_5.setText(_translate("MainWindow", "Service4"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Total"))
        self.clacBtn.setText(_translate("MainWindow", "Total"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
